---
output: github_document
---
   
<!-- README.md is generated from README.Rmd. Please edit that file --> 

    

```{r, include = FALSE}
knitr::opts_chunk$set(      
  collapse = TRUE,
  warning = FALSE,
  comment = "#>"          
)       
 
```


# featurette git repo 
 
<!-- badges: start -->
<!-- badges: end -->  

  

The goal of featurette is to feature and test out projects and packages! 

Repo: https://github.com/EvaMaeRey/featurette



```{r, results='asis', echo = F}
library(magrittr)
  
webpages <- fs::dir_ls(type = "file", recurse = T, glob = "*.html|*.pdf") %>% rev()
file_name_wo_extension <- webpages %>% stringr::str_remove(".html|.pdf")

webpages %>%    
  paste0("0. [",
         . ,
         "]",
         "(https://evamaerey.github.io/featurette/", ., 
         ") **[source](https://github.com/evamaerey/featurette/blob/master/",
         file_name_wo_extension,".Rmd",
         ")**\n") %>% 
  cat()     
```

---
 
# code to write new featurette

```{r, eval=FALSE}
new_experiment <- function(name){
  
  dir <- paste0(Sys.Date(),"-", name)
  
  dir.create(dir)
  readLines("template.Rmd") |>
    writeLines(con = paste0(dir,"/", name, ".Rmd"))
  
} 

new_experiment(name = "rladies-on-a-wire")



build_mp4 <- function(name){
  
  # create list of htmls
  webpages <- fs::dir_ls(type = "file", recurse = T, glob = "*.html") %>% rev()
  
  # grab target html
  target_html <- webpages[grep(name, webpages)][1]
  
  # build mp4
  xaringanBuilder::build_mp4(input = target_html)
  
} 

build_mp4("ggedgelist-gg-cran-extenders")

```


