---
title: "{ggcirclepack} Global Human Day featurette"
subtitle: "package is in initial stages"
author: ""
output:
  xaringan::moon_reader:
    lib_dir: libs
    css: [default, hygge, ninjutsu]
    nature:
      ratio: 16:9
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---




```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = F, message = F)
# remotes::install_github("EvaMaeRey/ggcirclepack")
```


`r flipbookr::chunk_reveal("feature", widths = c(1,1))`

---

```{r feature, echo = F, out.width="70%", fig.align='center'}
tt_url <- "https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2023/2023-09-12/global_human_day.csv" 
library(tidyverse)
library(ggcirclepack)

read_csv(tt_url) %>% 
  ggplot() + 
  aes(id = as_factor(Subcategory)) + 
  geom_polygon_circlepack() + 
  coord_equal() +
  aes(area = hoursPerDay) + 
  aes(fill = hoursPerDay) + 
  scale_fill_viridis_c(end = .8, ) +
  geom_text_circlepack(color = "white")+ 
  scale_size_continuous(range = c(0, 6)) + 
  theme_void() + 
  theme(legend.position = "none") +
  labs(title = "Time spent in a 'Global Human Day'") + 
  labs(subtitle = "using {packcircles} under the hood")
```



