---
title: "featurette"
subtitle: ""
date: "`r format(Sys.time(), '%B %d, %Y')`"
author: ""
output:
  xaringan::moon_reader:
    lib_dir: libs
    css: [default, hygge, ninjutsu]
    nature:
      ratio: 16:9
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
    seal: false
---




```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = F, message = F)
options(tidyverse.quiet = TRUE)
```

class: inverse, left, bottom
background-image: url(https://images.unsplash.com/photo-1542204165-65bf26472b9b?auto=format&fit=crop&q=80&w=1548&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D)
background-size: cover
# .Large[# My featurette]
## .small[featuring [{}]() ...]
#### .tiny[Gina Reynolds | 2023-10-25 |Image credit: Denise Jans, Upsplash]
???
Title 

---


```{r}
nc <- sf::st_read(system.file("shape/nc.shp", package="sf")) 

```

---

```{r}
library(ggplot2)
sf::st_read(system.file("shape/nc.shp", package="sf")) |>
  ggplot() + 
  geom_sf()
```


---

```{r}
layer_data()
```


---

`r flipbookr::chunk_reveal("feature", widths = c(1,1))`

---

```{r feature, echo = F, out.width="70%", fig.align='center', include = F}
nc |>
  ggnc::create_geometries_reference(
                            id_cols = c(NAME, FIPS)) ->
a_data_frame_ill_use_later
```


---

```{r}
ggnc::create_geometries_reference

ggnc::add_row_bounding_box

nc[1,] |> sf::st_bbox()
```


---

`r flipbookr::chunk_reveal("feature2", widths = c(1,1))`


```{r feature2, include= F}
st_bbox_df <- function(x){
  
  data.frame(xmin = sf::st_bbox(x)[1],
            xmax = sf::st_bbox(x)[2],
            ymin = sf::st_bbox(x)[3],
            ymax = sf::st_bbox(x)[4])
  
}

library(tidyverse)
nc |>
  dplyr::select(geometry) |>
  dplyr::mutate(bb = 
                  purrr::map(geometry, st_bbox_df)) |>
  unnest() 
```




---

### Check out more featurettes

- https://EvaMaeRey.github.io/featurette




```{css, eval = TRUE, echo = FALSE}
.remark-code{line-height: 1.5; font-size: 100%}
@media print {
  .has-continuation {
    display: block;
  }
}
```

